version: "3"

services:
    app:
        build:
            args:
                user: 1000
                uid: 1000
            context: .docker/php
            dockerfile: DockerFile
        working_dir: /var/www
        restart: unless-stopped
        volumes:
            - ./:/var/www
        networks:
            - backend-laravel

    nginxphp:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - backend-laravel
        depends_on:
            - app

    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: "root"
            POSTGRES_USER: "root"
            POSTGRES_DB: "laravel"
            PGDATA: /var/lib/postgresql/data/pgdata
        networks:
            - backend-laravel
volumes:
    postgres_data:
        driver: local

networks:
    backend-laravel:
        driver: bridge
